# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardsAPI', '0003_auto_20170620_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardsAPI.Deck'),
        ),
    ]
