# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardsAPI', '0004_auto_20170620_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cardsAPI.Deck'),
        ),
    ]
